name: Publish PowerShell Gallery
on:
  push:
    tags: ['v*']

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install PSResourceGet
        shell: pwsh
        run: Install-Module Microsoft.PowerShell.PSResourceGet -Force -Scope CurrentUser

      - name: Run Pester tests
        shell: pwsh
        run: |
          Import-Module "$PWD\NicolasAigner.SystemToolkit.psd1" -Force
          Invoke-Pester -CI

      - name: Publish module
        shell: pwsh
        env:
          PSGALLERY_APIKEY: ${{ secrets.PSGALLERY_APIKEY }}
        run: >
          Publish-PSResource -Path . `
                             -Repository PSGallery `
                             -ApiKey $env:PSGALLERY_APIKEY
